### ISSUE TITLE
Complete register.c

### ISSUE THREAD

**Issue by Cereal38** [Cereal38/arm-simulator#4]

**Comment by Cereal38** [comment]
Banch _register_

**Comment by RymaDhmn** [comment]
N'oublie pas d'essayer de coder en fonction du manuel ARM pour qu'on soit en accord (pages 42 et +) ^-^

**Comment by Cereal38** [comment]
Yep j'essaie, mais j'ai encore du mal à comprendre comment sont censés marcher les registres en fonctions des modes

**Comment by Cereal38** [comment]
Implémenté mais pas encore testé
